version: "3.7"

services:
  sheepmembers:
    image: multideskio/ci4:latest
    volumes:
      - multideskio:/var/www/html/writable
    environment:
      - CI4_GIT_REPO=    #https://github.com/codeigniter4/CodeIgniter4.git
      - CI_ENVIRONMENT=  #development #production #testing
      #- MIGRATIONS=true  FALSE = PULA AS MIGRATIONS
      - app_baseURL=
      - app_forceGlobalSecureRequests=
      - database_default_hostname=
      - database_default_database=
      - database_default_username=
      - database_default_password=
      - database_default_DBDriver=
      - database_default_DBPrefix=
      - database_default_port=3306
      - session_driver=
      - session_cookieName=
      - session_expiration=
      - session_savePath=
      - session_matchIP=
      - session_timeToUpdate=
      - session_regenerateDestroy=
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_DEFAULT_REGION=
      - AWS_ACCESS_KEY_ID_SES=
      - AWS_SECRET_ACCESS_KEY_SES=
      - AWS_DEFAULT_REGION_SES=
      - AWS_BUCKET=
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M   
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.multideskio.rule=Host(`SEU DOMINIO`)
        - traefik.http.routers.multideskio.entrypoints=websecure
        - traefik.http.routers.multideskio.tls.certresolver=letsencryptresolver
        - traefik.http.routers.multideskio.service=multideskio
        - traefik.http.services.multideskio.loadbalancer.server.port=80
        - traefik.http.services.multideskio.loadbalancer.passHostHeader=true

networks:
  default:
    name: minha_rede
    external: true

volumes:
  multideskio:
    driver: local